// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AudioPlayerController from "./audio_player_controller"
application.register("audio-player", AudioPlayerController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import StudioController from "./studio_controller"
application.register("studio", StudioController)

import TrackCardController from "./track_card_controller"
application.register("track-card", TrackCardController)

import PreviewController from "./preview_controller"
application.register("preview", PreviewController)