// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AudioPlayerController from "./audio_player_controller"
application.register("audio-player", AudioPlayerController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import StudioController from "./studio_controller"
application.register("studio", StudioController)

import TrackCardController from "./track_card_controller"
application.register("track-card", TrackCardController)

import AlbumCardController from "./album_card_controller"
application.register("album-card", AlbumCardController)

import LikeButtonController from "./like_button_controller"
application.register("like-button", LikeButtonController)

import FollowButtonController from "./follow_button_controller"
application.register("follow-button", FollowButtonController)

import PreviewController from "./preview_controller"
application.register("preview", PreviewController)