require "open3"
require "tempfile"
require "wahwah"

class AnalyzeTrackAudioJob < ApplicationJob
  queue_as :audio_analysis

  # Increment this when the stored waveform format changes. Metadata endpoints
  # only expose peaks generated by the current version, so older malformed data
  # is automatically ignored and re-queued for analysis.
  PEAKS_VERSION = 2

  # WaveSurfer expects pre-decoded peaks as channel arrays with alternating
  # min/max values for each horizontal point. A fixed “one loudest sample per
  # bucket” array looks like a comb of random bars, so we generate proper
  # min/max pairs similar to audiowaveform/exportPeaks output.
  PEAK_POINTS_PER_SECOND = 30
  MAX_PEAK_POINTS = 8_000
  MIN_PEAK_POINTS = 500
  PEAK_SAMPLE_RATE = 11_025
  CHANNELS = 2
  FRAME_BYTES = CHANNELS * 4

  def perform(track_id)
    track = Track.find_by(id: track_id)
    return unless track&.audio_file&.attached?

    track.update_columns(
      audio_analysis_status: "processing",
      audio_analysis_error: nil,
      updated_at: Time.current
    )

    blob = track.audio_file.blob
    extension = File.extname(blob.filename.to_s)

    Tempfile.create(["track-#{track.id}-", extension]) do |file|
      # ActiveStorage returns audio bytes as binary (ASCII-8BIT). Tempfile is
      # text/UTF-8 by default, so writing MP3/FLAC/OGG bytes to it can raise:
      # Encoding::UndefinedConversionError: "\xF0" from ASCII-8BIT to UTF-8.
      # Keep the temporary audio file in binary mode from the first write.
      file.binmode

      blob.download { |chunk| file.write(chunk.b) }
      file.flush
      file.rewind

      duration = read_duration(file.path)
      peaks = build_peaks(file.path, duration)

      track.update!(
        duration: duration.ceil.clamp(1, 1_799),
        audio_peaks: peaks,
        audio_peaks_version: peaks.present? ? PEAKS_VERSION : nil,
        audio_analysis_status: peaks.present? ? "ready" : "metadata_ready",
        audio_analysis_error: nil,
        audio_analyzed_at: Time.current
      )
    end
  rescue StandardError => error
    Rails.logger.error("AnalyzeTrackAudioJob failed for track ##{track_id}: #{error.class}: #{error.message}")

    if (track = Track.find_by(id: track_id))
      track.update_columns(
        audio_analysis_status: "failed",
        audio_analysis_error: error.message.to_s.truncate(500),
        updated_at: Time.current
      )
    end
  end

  private

  def read_duration(path)
    ffprobe_duration = read_duration_with_ffprobe(path)
    return ffprobe_duration if ffprobe_duration.to_f.positive?

    duration = WahWah.open(path).duration.to_f
    raise "Не удалось определить длительность аудиофайла" if duration <= 0

    duration
  end

  def read_duration_with_ffprobe(path)
    return nil unless ffprobe_available?

    stdout, _stderr, status = Open3.capture3(
      "ffprobe",
      "-v", "error",
      "-show_entries", "format=duration",
      "-of", "default=noprint_wrappers=1:nokey=1",
      path
    )

    return nil unless status.success?

    duration = stdout.to_s.strip.to_f
    duration.positive? ? duration : nil
  rescue StandardError => error
    Rails.logger.warn("Не удалось прочитать duration через ffprobe: #{error.class}: #{error.message}")
    nil
  end

  def build_peaks(path, duration)
    return [] unless ffmpeg_available?

    command = [
      "ffmpeg",
      "-hide_banner",
      "-loglevel", "error",
      "-i", path,
      "-vn",
      "-ac", CHANNELS.to_s,
      "-ar", PEAK_SAMPLE_RATE.to_s,
      "-f", "f32le",
      "pipe:1"
    ]

    peak_points = peak_points_for(duration)
    total_frames = [duration.to_f * PEAK_SAMPLE_RATE, 1].max
    frames_per_peak = [total_frames / peak_points, 1.0].max

    min_peaks = Array.new(CHANNELS) { Array.new(peak_points, 1.0) }
    max_peaks = Array.new(CHANNELS) { Array.new(peak_points, -1.0) }
    touched = Array.new(CHANNELS) { Array.new(peak_points, false) }

    frame_index = 0
    leftover = "".b

    Open3.popen3(*command) do |_stdin, stdout, stderr, wait_thread|
      stdout.binmode
      stderr.binmode

      until stdout.eof?
        chunk = leftover + stdout.readpartial(64.kilobytes)
        bytes_to_unpack = chunk.bytesize - (chunk.bytesize % FRAME_BYTES)
        leftover = chunk.byteslice(bytes_to_unpack, chunk.bytesize - bytes_to_unpack) || "".b
        samples = chunk.byteslice(0, bytes_to_unpack).unpack("e*")

        samples.each_slice(CHANNELS) do |frame|
          peak_index = [(frame_index / frames_per_peak).floor, peak_points - 1].min

          frame.each_with_index do |sample, channel_index|
            next unless sample

            sample = sample.clamp(-1.0, 1.0)
            min_peaks[channel_index][peak_index] = sample if sample < min_peaks[channel_index][peak_index]
            max_peaks[channel_index][peak_index] = sample if sample > max_peaks[channel_index][peak_index]
            touched[channel_index][peak_index] = true
          end

          frame_index += 1
        end
      end

      unless wait_thread.value.success?
        error_output = stderr.read.to_s.strip
        raise "ffmpeg не смог построить waveform#{": #{error_output}" if error_output.present?}"
      end
    end

    build_wave_surfer_peak_arrays(min_peaks, max_peaks, touched)
  rescue StandardError => error
    Rails.logger.warn("Не удалось построить peaks через ffmpeg: #{error.class}: #{error.message}")
    []
  end

  def peak_points_for(duration)
    requested_points = (duration.to_f * PEAK_POINTS_PER_SECOND).ceil
    requested_points.clamp(MIN_PEAK_POINTS, MAX_PEAK_POINTS)
  end

  def build_wave_surfer_peak_arrays(min_peaks, max_peaks, touched)
    min_peaks.each_index.map do |channel_index|
      min_peaks[channel_index].each_index.flat_map do |point_index|
        if touched[channel_index][point_index]
          [
            min_peaks[channel_index][point_index].round(4),
            max_peaks[channel_index][point_index].round(4)
          ]
        else
          [0.0, 0.0]
        end
      end
    end
  end

  def ffprobe_available?
    _stdout, _stderr, status = Open3.capture3("ffprobe", "-version")
    status.success?
  rescue Errno::ENOENT
    false
  end

  def ffmpeg_available?
    _stdout, _stderr, status = Open3.capture3("ffmpeg", "-version")
    status.success?
  rescue Errno::ENOENT
    false
  end
end
